### ISSUE TITLE
WARN  com.arangodb.ArangoDB$Builder - Usage of VelocyPack Java serialization is now deprecated for removal

### ISSUE THREAD

**Issue by menesty** [GoodforGod/micronaut-arangodb#20]
io.micronaut.configuration.arango.ArangoAccessorFactory
update serialize to ArangoJack arangoJack = new ArangoJack();
https://www.arangodb.com/docs/stable/drivers/java-reference-serialization.html

it will be good to have possiblity configure this ArangoJack

**Comment by GoodforGod** [comment]
I'll check how to do such configuration in next release
