### ISSUE TITLE
Support ArangoDB Driver 7.0

### ISSUE THREAD

**Issue by rashtao** [GoodforGod/micronaut-arangodb#22]
A first snapshot release of ArangoDB Java Driver version 7.0 has been published, see https://github.com/arangodb/arangodb-java-driver/releases/tag/v7.0.0-SNAPSHOT-1.

Please keep in mind that this is a snapshot release. It is suited for testing purposes only and is NOT for production usage. It is solely meant to allow users and libraries maintainers trying out the new features and reviewing the API changes, before the general availability of the stable release.

You might consider verifying if your project is compatible with it and can benefit from the new added features.

Here you can find a detailed description of the new features and API changes:
https://github.com/arangodb/arangodb-java-driver/blob/v7/docs

Feedback and questions are welcome in our dedicated `driverdev` Slack channel (https://arangodb-community.slack.com/archives/C1R1A2TFC).

--
Michele Rastelli
Java Engineer
ArangoDB GmbH

**Comment by GoodforGod** [comment]
Thanks for reaching out @rashtao , I'll start preparing major release with 7.0.0 driver support in future

**Comment by rashtao** [comment]
Hi @GoodforGod ,


ArangoDB Java Driver version 7.0 reached RC stage and the API can now be considered final: https://github.com/arangodb/arangodb-java-driver/releases/tag/v7.0.0-RC.3

Among other improvements, the following features migth be interesting for this project:

- a new [Serialization API](https://github.com/arangodb/arangodb-java-driver/blob/v7/docs/v7_java-reference-serialization.md) with dataformat-agnostic interface [ArangoSerde](https://github.com/arangodb/arangodb-java-driver/blob/v7/core/src/main/java/com/arangodb/serde/ArangoSerde.java) for serializing and deserializing user data. I.e. this can be implemented using Micronaut Serialization.
- a new [Configuration API](https://github.com/arangodb/arangodb-java-driver/blob/v7/docs/v7_java-reference-setup.md#driver-setup), which could be implemented to integrate with Micronaut Configuration
- a [shaded](https://github.com/arangodb/arangodb-java-driver/blob/v7/docs/v7_java.md#arangodb-java-driver-shaded) variant of the driver, beneficial in case of transitive dependencies convergence problems
- improved support to [GraalVM Native Image](https://github.com/arangodb/arangodb-java-driver/blob/v7/docs/v7_java.md#graalvm-native-image)

Feedback and questions are welcome!

**Comment by GoodforGod** [comment]
Hi @rashtao !

Great to hear this, nice features!

Will start working on new release

**Comment by GoodforGod** [comment]
Some useless API is missing in `ArangoConfigProperties`, it can be loaded only from file but in prev version I could use InputStream and directly create supply it, now the only option is to load from file..

It would be useless to get method `ArangoConfigProperties.fromProperies` and supply `Properties` directly
@rashtao

**Comment by rashtao** [comment]
`ArangoConfigProperties` is just an interface and the implementation of this is not responsibility of the driver (except the default implementation provided by `ArangoConfigProperties#fromFile()`).

E.g. implementations could supply configuration properties coming from different sources like ConfigMaps, system properties, remote stores, frameworks integrations, etc.

An interesting case for this library would be providing an adapter for Micronaut ConfigurationProperties , see https://github.com/arangodb-helper/arango-micronaut-native-example/blob/main/src/main/kotlin/com/example/ArangoConfig.kt

**Comment by rashtao** [comment]
Version [7.0.0](https://github.com/arangodb/arangodb-java-driver/releases/tag/v7.0.0) has been just released.
